### ISSUE TITLE
Line on screen.

### ISSUE THREAD

**Issue by Morscire** [plaguesec/PlagueSecOS#1]
### Issue
Line on screen. Xfce 4.12 problem.

### Solution
Can be fixed in Settings > Windows Manager Tweaks > Compositor > Uncheck "Show shadows under dock windows"

### References
https://nochkawtf.wordpress.com/2015/05/03/horizontal-line-across-screen-on-xfce/
https://bbs.archlinux.org/viewtopic.php?id=194770

**Comment by itsjeffersonli** [comment]
it is already fix in our repository will update in a few days

**Comment by itsjeffersonli** [comment]
it is already updated you may check on this commit

https://github.com/plaguesec/PlagueSecOS/commit/6822f7b4a7171bfc62377002e03c79eb7b1bb36c
